In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7])
type(arr)


numpy.ndarray

In [3]:
list1=[1,2,3,4,5,6,7]
arr2 = np.array(list1)
type(arr2)

numpy.ndarray

In [5]:
sumArry = arr+arr2
sumArry

array([ 2,  4,  6,  8, 10, 12, 14])

## Dimensions in Array


In [6]:
## 0-D Array
arr = np.array(42)
arr

array(42)

In [8]:
## 2d Array

arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
## 3D Array
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### Checking dimension of Array


In [12]:
import numpy as np

a = np.array(7)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[5,6,7]],[[8,9,10],[11,12,13]]])

In [17]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [20]:
arr = np.array([1,2,3,4],ndmin=5)
arr

array([[[[[1, 2, 3, 4]]]]])